import User from './user.model.js';
import Facility from './facility.model.js';
import Court from './court.model.js';
import CourtType from './court_type.model.js';
import Booking from './booking.model.js';
import BookingSlot from './booking_slot.model.js';
import Product from './product.model.js';
import ProductVariant from './product_variant.model.js';
import Order from './order.model.js';
import OrderItem from './order_item.model.js';
import InventoryLevel from './inventory_level.model.js';
import PriceConfig from './price_config.model.js';
import StaffProfile from './staff_profile.model.js';
import InventoryMovement from './inventory_movement.model.js';
import Payment from './payment.model.js';
import AuditLog from './audit_log.model.js';
import RefreshToken from './refresh_token.model.js';
import Holiday from './holiday.model.js';
import SystemConfig from './system_config.model.js';
declare const models: {
    User: typeof User;
    Facility: typeof Facility;
    Court: typeof Court;
    CourtType: typeof CourtType;
    Booking: typeof Booking;
    BookingSlot: typeof BookingSlot;
    Product: typeof Product;
    ProductVariant: typeof ProductVariant;
    Order: typeof Order;
    OrderItem: typeof OrderItem;
    InventoryLevel: typeof InventoryLevel;
    PriceConfig: typeof PriceConfig;
    StaffProfile: typeof StaffProfile;
    RefreshToken: typeof RefreshToken;
    InventoryMovement: typeof InventoryMovement;
    Payment: typeof Payment;
    AuditLog: typeof AuditLog;
    Holiday: typeof Holiday;
    SystemConfig: typeof SystemConfig;
};
export default models;
//# sourceMappingURL=index.d.ts.map